image: registry.gitlab.com/tdely/go-hawk:latest

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test

before_script:
  - mkdir -p /go/src/gitlab.com/tdely /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/tdely/go-hawk
  - ln -s /go/src/gitlab.com/tdely /go/src/_/builds/tdely
  - export CC=clang-7
  - make dep

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master

lint_code:
  stage: test
  script:
    - make lint
